mysqld:
        image: "gjkdhr/centos:mysqld"
        ports:
                - "32768:3306"
        hostname: "container_mysql.zbit.com"

httpd:
        image: "gjkdhr/centos:httpd"
        ports:
                - "80:80"
        volumes:
                - "/mnt/web_root:/app"
        hostname: "container_server.zbit.com"
