version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  delete:
    enabled: true
  cache:
    layerinfo: inmmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  secret: admin
